### PR TITLE
Issues/68

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This PR addresses #67 and #68.

It allows the user to use a step size for the derivatives that is proportional to the width of the search space.

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
Any volunteers to review this PR? @elisachisari, @arthurmloureiro? 😅

**Comment by arthurmloureiro** [comment]
> Any volunteers to review this PR? @elisachisari, @arthurmloureiro? 😅

I can review it!

**Review by arthurmloureiro — APPROVED** [review]
All seems good!

**Comment by fjaviersanchez** [comment]
Thank you! @arthurmloureiro

**Pull request merged**
