### PR TITLE
Issues/20

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This PR addresses #20

### CODE REVIEW

**Comment by biancasersante** [comment]
Hi! I have noticed that although the double plots for w_0-w_a and omega_c-sigma_8 can indeed be obtained (for instance running the y1 example), they both are centered in (0,0) (e.g. instead of (-1,0) in the case of w_0-w_a ).

**Comment by fjaviersanchez** [comment]
Sorry about that, I should probably document this somewhere. The default is that all ellipses are centered in (0,0), but that can be changed in the configuration file by passing the parameter centers. For example, in `srd_y1_3x2pt.yaml` you can modify this section:
```
postprocess:
  latex_table: output_fishery1/latex_table.tex
  triangle_plot: output_fishery1/triangle_plot.pdf
  pairplots: [(w0, wa), (omega_c, sigma8)]
  CL: 0.68
```
To this
```
postprocess:
  latex_table: output_fishery1/latex_table.tex
  triangle_plot: output_fishery1/triangle_plot.pdf
  pairplots: [(w0, wa), (omega_c, sigma8)]
  CL: 0.68
  centers: [0.25, 0.81, -1, 0, 0.67, 0.96, 0, 0, 1, 5, 0, 1.5, 1.7, 1.9, 2.1, 2.3, 0, 0, 0, 0, 0]
```
Where centers are the value of the parameters with the same order as you pass them in the `parameters` section of the config file. I can also draw them by default in their nominal value if that's more helpful.

**Review by elisachisari — CHANGES_REQUESTED** [review]
This works, thanks. Can we make the change for the center of the ellipses to be drawn at the nominal value?

**Review by elisachisari — APPROVED** [review]
Thanks for the further changes. I checked and now the contours are centered at the fiducial params.

**Pull request merged**
