### PR TITLE
draws more than 1 confidence interval

### PR DESCRIPTION
**Pull request by arthurmloureiro**
Allows for at least 3 Credible Levels to be plot and also to output to table.

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
Nice! Thank you for the contribution, this is great. I just made some updates that I think will conflict with these... Would you mind pulling the latest master/rebasing? I can jump on a call and discuss what I did.

**Comment by arthurmloureiro** [comment]
> Nice! Thank you for the contribution, this is great. I just made some updates that I think will conflict with these... Would you mind pulling the latest master/rebasing? I can jump on a call and discuss what I did.

Hi @fjaviersanchez ! 
I will try to merge master into this branch ! We have a call scheduled right now in the forecasting workshop, but I will try to understand your changes and merge that into this PR. :D

**Comment by arthurmloureiro** [comment]
@fjaviersanchez : conflicts resolved! Merged the main into this branch 😄

**Review by fjaviersanchez — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
